// Autos Aragon Car Catalog Dataset
window.CARS_DATA = [
  {
    "id": "audi-q5-2-0tfsi-quattro-tiptronic-advance-edition",
    "brand": "Audi",
    "title": "Audi Q5 2.0 TFSI Quattro Tiptronic Advance",
    "slug": "audi-q5-2-0tfsi-quattro-tiptronic-advance-edition",
    "specs": {
      "precio": "€1€9€.€9€9€0€ €€",
      "km": "102.000 km",
      "año": "17/03/2015",
      "combustible": "Gasolina",
      "cambio": "Automático Tiptronic",
      "color": "Blanco",
      "puertas": "5",
      "plazas": "5",
      "etiqueta": "C",
      "potencia": "225 CV",
      "garantia": "Garantía 12 Meses Nacional y Cambio de Nombre incluidos"
    },
    "equipment": [
      "-Tracción Quattro.",
      "-Reproductor de CD",
      "-Airbag para conductor y acompañante",
      "-Retrovisores exteriores: plegables y calefactables eléctricamente",
      "-Programa electrónico de estabilización (ESP)",
      "-Control de distancia de estacionamiento",
      "-Tiptronic",
      "-Faros de xénon",
      "-Volante deportivo multifunción forrado en cuero",
      "-Pantalla multifunción/ordenador de a bordo",
      "-Climatizador",
      "-Llantas de aleación 8J x 18",
      "-Indicador de presión de neumáticos",
      "-Airbags laterales delanteros y traseros con airbag de cortina",
      "-Ajuste manual de altura para los asientos delanteros",
      "-Asientos deportivos delanteros",
      "-Parabrisas con cristal termoaislante",
      "-Control de velocidad",
      "-Control de tracción",
      "-Tapicería mixta piel tela.",
      "-Sensor de luz.",
      "-Portón eléctrico."
    ],
    "comments": "1 SOLO PROPIETARIO",
    "images": [
      "assets/cars/audi-q5-2-0tfsi-quattro-tiptronic-advance-edition/img_01.jpg",
      "assets/cars/audi-q5-2-0tfsi-quattro-tiptronic-advance-edition/img_02.jpg",
      "assets/cars/audi-q5-2-0tfsi-quattro-tiptronic-advance-edition/img_03.jpg",
      "assets/cars/audi-q5-2-0tfsi-quattro-tiptronic-advance-edition/img_04.jpg",
      "assets/cars/audi-q5-2-0tfsi-quattro-tiptronic-advance-edition/img_05.jpg",
      "assets/cars/audi-q5-2-0tfsi-quattro-tiptronic-advance-edition/img_06.jpg",
      "assets/cars/audi-q5-2-0tfsi-quattro-tiptronic-advance-edition/img_07.jpg",
      "assets/cars/audi-q5-2-0tfsi-quattro-tiptronic-advance-edition/img_08.jpg",
      "assets/cars/audi-q5-2-0tfsi-quattro-tiptronic-advance-edition/img_09.jpg",
      "assets/cars/audi-q5-2-0tfsi-quattro-tiptronic-advance-edition/img_10.jpg",
      "assets/cars/audi-q5-2-0tfsi-quattro-tiptronic-advance-edition/img_11.jpg",
      "assets/cars/audi-q5-2-0tfsi-quattro-tiptronic-advance-edition/img_12.jpg",
      "assets/cars/audi-q5-2-0tfsi-quattro-tiptronic-advance-edition/img_13.jpg",
      "assets/cars/audi-q5-2-0tfsi-quattro-tiptronic-advance-edition/img_14.jpg",
      "assets/cars/audi-q5-2-0tfsi-quattro-tiptronic-advance-edition/img_15.jpg",
      "assets/cars/audi-q5-2-0tfsi-quattro-tiptronic-advance-edition/img_16.jpg"
    ],
    "thumbnail": "assets/cars/audi-q5-2-0tfsi-quattro-tiptronic-advance-edition/img_01.jpg",
    "price_num": 19990,
    "cuota": "235 €/mes",
    "body_type": "SUV"
  },
  {
    "id": "bmw-x1-2-0d-xdrive-m-sport-pro",
    "brand": "BMW",
    "title": "BMW X1 2.0d xDrive M Sport Pro",
    "slug": "bmw-x1-2-0d-xdrive-m-sport-pro",
    "specs": {
      "precio": "€5€2€.€0€0€0€ €€",
      "km": "20.000 km",
      "año": "Marzo 2024",
      "combustible": "Diésel Microhíbrido",
      "cambio": "Automático Steptronic",
      "color": "Blanco Mineral",
      "puertas": "5",
      "plazas": "5",
      "etiqueta": "ECO",
      "potencia": "170 CV",
      "garantia": "Garantía oficial BMW hasta Marzo 2028"
    },
    "equipment": [
      "Pantalla táctil multimedia con Apple CarPlay & Android Auto",
      "Cámara de visión trasera con sensores de aparcamiento",
      "Climatizador automático bizona",
      "Llantas de aleación ligera",
      "Control de crucero adaptativo y limitador de velocidad",
      "Faros LED automáticos y sensor de lluvia",
      "Volante multifunción de cuero y arranque sin llave (Keyless)",
      "Asistente de mantenimiento de carril y frenada de emergencia"
    ],
    "comments": "GARANTÍA BMW HASTA MARZO DEL 2028",
    "images": [
      "assets/cars/bmw-x1-2-0d-xdrive-m-sport-pro/img_01.jpg",
      "assets/cars/bmw-x1-2-0d-xdrive-m-sport-pro/img_02.jpg",
      "assets/cars/bmw-x1-2-0d-xdrive-m-sport-pro/img_03.jpg",
      "assets/cars/bmw-x1-2-0d-xdrive-m-sport-pro/img_04.jpg",
      "assets/cars/bmw-x1-2-0d-xdrive-m-sport-pro/img_05.jpg",
      "assets/cars/bmw-x1-2-0d-xdrive-m-sport-pro/img_06.jpg",
      "assets/cars/bmw-x1-2-0d-xdrive-m-sport-pro/img_07.jpg",
      "assets/cars/bmw-x1-2-0d-xdrive-m-sport-pro/img_08.jpg",
      "assets/cars/bmw-x1-2-0d-xdrive-m-sport-pro/img_09.jpg",
      "assets/cars/bmw-x1-2-0d-xdrive-m-sport-pro/img_10.jpg",
      "assets/cars/bmw-x1-2-0d-xdrive-m-sport-pro/img_11.jpg",
      "assets/cars/bmw-x1-2-0d-xdrive-m-sport-pro/img_12.jpg",
      "assets/cars/bmw-x1-2-0d-xdrive-m-sport-pro/img_13.jpg",
      "assets/cars/bmw-x1-2-0d-xdrive-m-sport-pro/img_14.jpg",
      "assets/cars/bmw-x1-2-0d-xdrive-m-sport-pro/img_15.jpg",
      "assets/cars/bmw-x1-2-0d-xdrive-m-sport-pro/img_16.jpg"
    ],
    "thumbnail": "assets/cars/bmw-x1-2-0d-xdrive-m-sport-pro/img_01.jpg",
    "price_num": 52000,
    "cuota": "580 €/mes",
    "body_type": "SUV"
  },
  {
    "id": "hyundai-i10-4304-mrr",
    "brand": "Hyundai",
    "title": "Hyundai i10 1.0 MPI Klass",
    "slug": "hyundai-i10-4304-mrr",
    "specs": {
      "precio": "€1€3€.€6€9€0€ €€",
      "km": "15.000 km",
      "año": "27/04/2022",
      "combustible": "Gasolina",
      "cambio": "Manual",
      "color": "Blanco Polar",
      "puertas": "5",
      "plazas": "5",
      "etiqueta": "C",
      "potencia": "67 CV",
      "garantia": "Garantía 12 Meses Nacional y Cambio de Nombre incluidos"
    },
    "equipment": [
      "-8 Airbags",
      "-Control de crucero con limitador",
      "-Control de estabilidad (ESP)",
      "-Control de presión en neumáticos",
      "-Control de tracción",
      "-Cámara de visión trasera",
      "-4 altavoces",
      "-Android Auto/Apple CarPlay",
      "-Conexión Bluetooth para teléfono móvil",
      "-Dos puertos USB en consola central",
      "-Pantalla táctil a color de 20,3 cm (8&quot;)",
      "-Alarma de cambio involuntario de carril",
      "-Antibloqueo de frenos (ABS)",
      "-Asistente de arranque en pendiente (HAC)",
      "-Asistente de cambio involuntario de carril",
      "-Asistente de frenada",
      "-Asistente de frenada de emergencia",
      "-Front Assist con detección de peatones",
      "-Asistente de luz de carretera",
      "-Detección de fatiga del conductor",
      "-Distribución electrónica de frenado (EBD)",
      "-Luz de frenada de emergencia",
      "-Luz diurna",
      "-Mandos multifunción en volante",
      "-Ordenador de viaje",
      "-Aire acondicionado",
      "-Asiento del conductor con ajuste de altura",
      "-Cierre centralizado",
      "-Elevalunas eléctricos delanteros",
      "-Elevalunas eléctricos traseros",
      "-Función Stop&amp;Go",
      "-Luces automáticas",
      "-Mando de apertura a distancia",
      "-Retrovisores exteriores orientables eléctricamente",
      "-Cuadro con pantalla multifunción de 8,9 cm (3,5&quot;)",
      "-Luces traseras LED",
      "-Volante y pomo revestidos de cuero",
      "-4 altavoces",
      "-Android Auto/Apple CarPlay",
      "-Conexión Bluetooth para teléfono móvil",
      "-Dos puertos USB en consola central",
      "-Pantalla táctil a color de 20,3 cm (8&quot;)",
      "-Radio",
      "-Kit de reparación de neumáticos",
      "De serie",
      "-Llantas de aleación 38 cm (185/55 R15)"
    ],
    "comments": "GARANTIA HYUNDAI HASTA 26-5-2029 HISTORIAL DE MANTENIMIENTO EN SERVICIO OFICIAL.",
    "images": [
      "assets/cars/hyundai-i10-4304-mrr/img_01.jpg",
      "assets/cars/hyundai-i10-4304-mrr/img_02.jpg",
      "assets/cars/hyundai-i10-4304-mrr/img_03.jpg",
      "assets/cars/hyundai-i10-4304-mrr/img_04.jpg",
      "assets/cars/hyundai-i10-4304-mrr/img_05.jpg",
      "assets/cars/hyundai-i10-4304-mrr/img_06.jpg",
      "assets/cars/hyundai-i10-4304-mrr/img_07.jpg",
      "assets/cars/hyundai-i10-4304-mrr/img_08.jpg",
      "assets/cars/hyundai-i10-4304-mrr/img_09.jpg",
      "assets/cars/hyundai-i10-4304-mrr/img_10.jpg",
      "assets/cars/hyundai-i10-4304-mrr/img_11.jpg",
      "assets/cars/hyundai-i10-4304-mrr/img_12.jpg",
      "assets/cars/hyundai-i10-4304-mrr/img_13.jpg",
      "assets/cars/hyundai-i10-4304-mrr/img_14.jpg",
      "assets/cars/hyundai-i10-4304-mrr/img_15.jpg",
      "assets/cars/hyundai-i10-4304-mrr/img_16.jpg"
    ],
    "thumbnail": "assets/cars/hyundai-i10-4304-mrr/img_01.jpg",
    "price_num": 13690,
    "cuota": "160 €/mes",
    "body_type": "Urbano"
  },
  {
    "id": "kia-picanto-1-0dpi-concept",
    "brand": "Kia",
    "title": "Kia Picanto 1.0 DPI Concept",
    "slug": "kia-picanto-1-0dpi-concept",
    "specs": {
      "precio": "€1€4€.€9€9€0€ €€",
      "km": "4.000 km",
      "año": "27/01/2025",
      "combustible": "Gasolina",
      "cambio": "Manual",
      "color": "Gris Metalizado",
      "puertas": "5",
      "plazas": "5",
      "etiqueta": "C",
      "potencia": "63 CV",
      "garantia": "Garantía oficial KIA 7 años"
    },
    "equipment": [
      "8 Airbags",
      "Navegador",
      "Pantalla central de 20,3 cm (8&quot;)",
      "Control de crucero",
      "Control de estabilidad",
      "Control de presión de neumáticos",
      "Control de tracción",
      "Cámara de visión trasera",
      "4 altavoces",
      "Android Auto y Apple CarPlay",
      "Conexión Bluetooth para teléfono móvil",
      "Conexión USB y puerto de carga rápida USB",
      "Alerta de cambio involuntario de carril",
      "Alerta de fatiga del conductor",
      "Antibloqueo de frenos (ABS)",
      "Asistente de cambio involuntario de carril",
      "Asistente de frenada",
      "Asistente de frenada de emergencia",
      "Ayuda de aparcamiento trasero",
      "Ayuda de arranque en cuesta",
      "Dirección asistida eléctrica",
      "Distribución electrónica de frenado (EBD)",
      "Mandos multifunción en volante",
      "Ordenador de viaje",
      "Reconocimiento de señales de tráfico",
      "Termómetro exterior",
      "Aire acondicionado",
      "Asiento del conductor con ajuste de altura",
      "Cierre centralizado",
      "Elevalunas eléctricos delanteros y traseros",
      "Función Start &amp; Stop",
      "Luces automáticas",
      "Lunas tintadas",
      "Mando de apertura a distancia",
      "Retrovisores exteriores orientables eléctricamente",
      "Panel de instrumentos digital de 10,7 cm (4,2&quot;)",
      "Pintura metalizada",
      "Radio digital",
      "Reconocimiento de voz",
      "Equipo reparapinchazos"
    ],
    "comments": "Único dueño particular. Revisión pasada en servicio oficial. GARANTÍA HASTA 26-1-2032",
    "images": [
      "assets/cars/kia-picanto-1-0dpi-concept/img_01.jpg",
      "assets/cars/kia-picanto-1-0dpi-concept/img_02.jpg",
      "assets/cars/kia-picanto-1-0dpi-concept/img_03.jpg",
      "assets/cars/kia-picanto-1-0dpi-concept/img_04.jpg",
      "assets/cars/kia-picanto-1-0dpi-concept/img_05.jpg",
      "assets/cars/kia-picanto-1-0dpi-concept/img_06.jpg",
      "assets/cars/kia-picanto-1-0dpi-concept/img_07.jpg",
      "assets/cars/kia-picanto-1-0dpi-concept/img_08.jpg",
      "assets/cars/kia-picanto-1-0dpi-concept/img_09.jpg",
      "assets/cars/kia-picanto-1-0dpi-concept/img_10.jpg",
      "assets/cars/kia-picanto-1-0dpi-concept/img_11.jpg",
      "assets/cars/kia-picanto-1-0dpi-concept/img_12.jpg",
      "assets/cars/kia-picanto-1-0dpi-concept/img_13.jpg",
      "assets/cars/kia-picanto-1-0dpi-concept/img_14.jpg",
      "assets/cars/kia-picanto-1-0dpi-concept/img_15.jpg",
      "assets/cars/kia-picanto-1-0dpi-concept/img_16.jpg"
    ],
    "thumbnail": "assets/cars/kia-picanto-1-0dpi-concept/img_01.jpg",
    "price_num": 14990,
    "cuota": "175 €/mes",
    "body_type": "Urbano"
  },
  {
    "id": "mazda-cx5-2-0-homura",
    "brand": "Mazda",
    "title": "Mazda CX-5 2.0 Skyactiv-G 165CV Homura",
    "slug": "mazda-cx5-2-0-homura",
    "specs": {
      "precio": "€2€5€.€9€9€0€ €€",
      "km": "36.000 km",
      "año": "15/06/2022",
      "combustible": "Gasolina Skyactiv-G",
      "cambio": "Automático 6 vel.",
      "color": "Soul Red Crystal Metallic",
      "puertas": "5",
      "plazas": "5",
      "etiqueta": "C",
      "potencia": "165 CV",
      "garantia": "Garantía 12 Meses Nacional y Cambio de Nombre incluidos"
    },
    "equipment": [
      "Alarma de cambio involuntario de carril",
      "Tapicería de símil cuero y piel vuelta con costuras en rojo",
      "Volante calefactado",
      "Volante y palanca de cambios en cuero",
      "Llantas de aleación 48 cm (225/55 R19) Negras",
      "Asistencia a la frenada en ciudad delantero y trasero con reconocimiento de peatones",
      "Asistente de cambio involuntario de carril",
      "Asistente de frenado (EBA)",
      "Asis­ten­te de ar­ran­que en cues­ta (HHA)",
      "Control automático de luces de carretera (HBC)",
      "Control de crucero adaptativo por radar (MRCC)",
      "Sensores de aparcamiento",
      "Sensor de luz",
      "10 altavoces",
      "4 puertos USB (2 delante y 2 detrás)",
      "Android Auto / Apple CarPlay",
      "Cargador inalámbrico para móvil",
      "Conexión AUX",
      "Conexión Bluetooth para telefóno móvil",
      "HMI Commander (manejo de sistema multimedia)",
      "Navegador",
      "Pantalla central de 26 cm (10,25&quot;) MZD Connect",
      "Radio digital DAB",
      "Sistema de sonido BOSE",
      "Monitor de visión 360º",
      "Control de estabilidad (DSC)",
      "Control de presión en neumáticos",
      "Control de tracción",
      "Con­t­rol de án­gu­lo muer­to avan­za­do (BSM)",
      "Cámara de visión trasera",
      "De­tec­tor de trá­fi­co tra­se­ro (RCTA)",
      "Distribución electrónica de frenado (EBD)",
      "Faros Smart Full LED",
      "Faros adaptativos",
      "Frenada de emergencia pre-impacto (SBS) con alerta de obstrucción delantera",
      "Head Up Display",
      "Luz diurna LED",
      "Reconocimiento de señales de tráfico",
      "Retrovisores exteriores con calefacción",
      "Acceso sin llave",
      "Arranque sin llave",
      "Asientos delanteros calefactados",
      "Asientos delanteros regulables en altura",
      "Climatizador bizona",
      "Corte de ralentí i-stop",
      "Eyectores de lavaparabrisas con calefacción",
      "Función de luces coming &amp; leaving home",
      "Portón trasero eléctrico",
      "Retrovisores exteriores plegables eléctricamente",
      "Cuadro de mandos con pantalla de 17,8 cm (7&quot;)"
    ],
    "comments": "1 SOLO PROPIETARIO PARTICULAR. TODOS LOS MANTENIMIENTOS EN SERVICIO OFICIAL. GARANTIA MAZDA HASTA 21-12-2028",
    "images": [
      "assets/cars/mazda-cx5-2-0-homura/img_01.jpg",
      "assets/cars/mazda-cx5-2-0-homura/img_02.jpg",
      "assets/cars/mazda-cx5-2-0-homura/img_03.jpg",
      "assets/cars/mazda-cx5-2-0-homura/img_04.jpg",
      "assets/cars/mazda-cx5-2-0-homura/img_05.jpg",
      "assets/cars/mazda-cx5-2-0-homura/img_06.jpg",
      "assets/cars/mazda-cx5-2-0-homura/img_07.jpg",
      "assets/cars/mazda-cx5-2-0-homura/img_08.jpg",
      "assets/cars/mazda-cx5-2-0-homura/img_09.jpg",
      "assets/cars/mazda-cx5-2-0-homura/img_10.jpg",
      "assets/cars/mazda-cx5-2-0-homura/img_11.jpg",
      "assets/cars/mazda-cx5-2-0-homura/img_12.jpg",
      "assets/cars/mazda-cx5-2-0-homura/img_13.jpg",
      "assets/cars/mazda-cx5-2-0-homura/img_14.jpg",
      "assets/cars/mazda-cx5-2-0-homura/img_15.jpg",
      "assets/cars/mazda-cx5-2-0-homura/img_16.jpg"
    ],
    "thumbnail": "assets/cars/mazda-cx5-2-0-homura/img_01.jpg",
    "price_num": 25990,
    "cuota": "295 €/mes",
    "body_type": "SUV"
  },
  {
    "id": "mitsibishi-eclipse-cross",
    "brand": "Mitsubishi",
    "title": "Mitsubishi Eclipse Cross 150T Motion",
    "slug": "mitsibishi-eclipse-cross",
    "specs": {
      "precio": "€1€6€.€4€9€0€ €€",
      "km": "59.000 km",
      "año": "29/05/2019",
      "combustible": "Gasolina",
      "cambio": "Manual 6 vel.",
      "color": "Gris Titanio",
      "puertas": "Asiento del conductor con ajuste de altura",
      "plazas": "5",
      "etiqueta": "C",
      "potencia": "163 CV",
      "garantia": "Garantía 12 Meses Nacional y Cambio de Nombre incluidos"
    },
    "equipment": [
      "Control de crucero y limitador de velocidad",
      "Control de estabilidad (ASTC)",
      "Control de tracción",
      "Cámara de visión trasera",
      "Smartphone link Display Audio (Apple CarPlay &amp; Google Android Auto)",
      "Climatizador bizona",
      "Head Up Display (HUD)",
      "Distribución electrónica de frenado (EBD)",
      "Faros Bi-LED",
      "Faros antiniebla",
      "Sensor de luz",
      "Alerta de salida de carril (LDW)",
      "Mitigación de colisión frontal (FCM) con función de detección de peatones",
      "Antibloqueo de frenos (ABS)",
      "Asistencia a la frenada (BAS)",
      "Asistencia de arranque en cuesta (HSA)",
      "Sensores de aparcamiento delanteros y traseros",
      "Control automático de luces de carretera (AHB)",
      "Función de desconexión para airbag de pasajero",
      "Airbag de rodilla para conductor",
      "Airbag frontal conductor",
      "Airbag frontal pasajero",
      "Airbags de cabeza delanteros y traseros",
      "Airbags laterales delanteros",
      "Conexión Bluetooth para teléfono móvil",
      "Pantalla táctil de 17,8 cm",
      "Radio digital DAB",
      "Touchpad controller en consola central (para SDA y Apple CarPlay)",
      "2 puertos USB",
      "Llantas de aleación de 18”",
      "Lavafaros",
      "Luneta térmica",
      "Luz diurna LED",
      "Mandos multifunción en volante",
      "Monitorización de presión de los neumáticos (TPMS)",
      "Reconocimiento de señales de tráfico",
      "Retrovisor interior fotosensible",
      "Retrovisores exteriores con calefacción",
      "Señalización de frenada de emergencia (ESS)",
      "Termómetro exterior",
      "Apertura de puertas sin llave (KOS)",
      "Asiento del conductor con ajuste de altura",
      "Asiento trasero deslizante",
      "Cierre centralizado",
      "Cristales traseros con tratamiento de privacidad",
      "Elevalunas eléctricos delanteros y traseros",
      "Encendido del motor sin llave",
      "Función Coming Home y Welcome",
      "Parada y arranque automático (AS&amp;G)",
      "Retrovisores exteriores abatibles eléctricamente",
      "Retrovisores exteriores con ajuste eléctrico",
      "Cuadro de instrumentos con display LCD",
      "Embellecedor cromado en ventanas laterales y portón trasero",
      "Embellecedor lateral con inserción plata y molduras negras en pasos de rueda",
      "Frontal Dynamic Shield con elementos cromados y negro piano",
      "Luces traseras LED",
      "Retrovisores exteriores en el color de la carrocería",
      "Spoiler trasero",
      "Volante y pomo de palanca de cambios de cuero",
      "Antena de techo tipo aleta de tiburón"
    ],
    "comments": "VEHÍCULO MUY BIEN CONSERVADO",
    "images": [
      "assets/cars/mitsibishi-eclipse-cross/img_01.jpg",
      "assets/cars/mitsibishi-eclipse-cross/img_02.jpg",
      "assets/cars/mitsibishi-eclipse-cross/img_03.jpg",
      "assets/cars/mitsibishi-eclipse-cross/img_04.jpg",
      "assets/cars/mitsibishi-eclipse-cross/img_05.jpg",
      "assets/cars/mitsibishi-eclipse-cross/img_06.jpg",
      "assets/cars/mitsibishi-eclipse-cross/img_07.jpg",
      "assets/cars/mitsibishi-eclipse-cross/img_08.jpg",
      "assets/cars/mitsibishi-eclipse-cross/img_09.jpg",
      "assets/cars/mitsibishi-eclipse-cross/img_10.jpg",
      "assets/cars/mitsibishi-eclipse-cross/img_11.jpg",
      "assets/cars/mitsibishi-eclipse-cross/img_12.jpg",
      "assets/cars/mitsibishi-eclipse-cross/img_13.jpg",
      "assets/cars/mitsibishi-eclipse-cross/img_14.jpg",
      "assets/cars/mitsibishi-eclipse-cross/img_15.jpg",
      "assets/cars/mitsibishi-eclipse-cross/img_16.jpg"
    ],
    "thumbnail": "assets/cars/mitsibishi-eclipse-cross/img_01.jpg",
    "price_num": 16490,
    "cuota": "195 €/mes",
    "body_type": "SUV"
  },
  {
    "id": "nissan-qashqai-1-3-dig-t-160cv-acenta",
    "brand": "Nissan",
    "title": "Nissan Qashqai 1.3 DIG-T 160CV Acenta DCT",
    "slug": "nissan-qashqai-1-3-dig-t-160cv-acenta",
    "specs": {
      "precio": "€1€8€.€9€9€0€ €€",
      "km": "51.000 km",
      "año": "25/09/2020",
      "combustible": "Gasolina",
      "cambio": "Automático DCT",
      "color": "Gris Oscuro",
      "puertas": "Desactivación de airbag del pasajero delantero",
      "plazas": "Indicador de presión de neumaticos",
      "etiqueta": "C",
      "potencia": "160 CV",
      "garantia": "Garantía 12 Meses Nacional y Cambio de Nombre incluidos"
    },
    "equipment": [
      "Navegador + antena tiburón",
      "Conector MP3 (Aux-in 3,5 mm)",
      "Conexión Bluetooth con micrófono",
      "Pantalla táctil 18 cm en color",
      "Android Auto y Apple CarPlay",
      "Puerto USB",
      "Radio con lector de CD",
      "Cámara de visión trasera",
      "Climatizador bizona",
      "Llantas de 17 pulgadas.",
      "Control de crucero y limitador de velocidad",
      "Control de estabilidad (ESP)",
      "Control de tracción",
      "Sensores de aparcamiento delantero",
      "Sensores de aparcamiento trasero",
      "Pantalla TFT en color de 13 cm en cuadro de instrumentos",
      "Volante y pomo del cambio en cuero",
      "Airbag frontal conductor",
      "Airbag frontal pasajero",
      "Airbags de cabeza delanteros y traseros",
      "Airbags laterales delanteros",
      "Antibloqueo de frenos (ABS)",
      "Asistente a la frenada de emergencia",
      "Asistente de arranque en pendiente",
      "Aviso de cinturón no colocado",
      "Cierre de seguridad para niños en puertas traseras",
      "Desactivación de airbag del pasajero delantero",
      "Dirección asistida eléctrica",
      "Distribución electrónica de frenado (EBD)",
      "Faros antiniebla",
      "Fijaciones ISOFIX en plazas traseras exteriores",
      "Indicador de presión de neumaticos",
      "Luz de día LED",
      "Mandos multifunción en volante",
      "Retrovisores exteriores con calefacción",
      "Volante con ajuste horizontal",
      "Volante con ajuste vertical",
      "Activación automática de faros",
      "Apoyabrazos central delantero",
      "Freno de mano eléctrico",
      "Función Stop&amp;Start",
      "Limpiaparabrisas con sensor de lluvia",
      "Lunas tintadas",
      "Retrovisores exteriores abatibles eléctricamente",
      "Volante y pomo del cambio en cuero",
      "Asiento trasero abatible por partes (60/40)",
      "Divisor de carga para maletero"
    ],
    "comments": "1 SOLO PROPIETARIO P ARTICULAR",
    "images": [
      "assets/cars/nissan-qashqai-1-3-dig-t-160cv-acenta/img_01.jpg",
      "assets/cars/nissan-qashqai-1-3-dig-t-160cv-acenta/img_02.jpg",
      "assets/cars/nissan-qashqai-1-3-dig-t-160cv-acenta/img_03.jpg",
      "assets/cars/nissan-qashqai-1-3-dig-t-160cv-acenta/img_04.jpg",
      "assets/cars/nissan-qashqai-1-3-dig-t-160cv-acenta/img_05.jpg",
      "assets/cars/nissan-qashqai-1-3-dig-t-160cv-acenta/img_06.jpg",
      "assets/cars/nissan-qashqai-1-3-dig-t-160cv-acenta/img_07.jpg",
      "assets/cars/nissan-qashqai-1-3-dig-t-160cv-acenta/img_08.jpg",
      "assets/cars/nissan-qashqai-1-3-dig-t-160cv-acenta/img_09.jpg",
      "assets/cars/nissan-qashqai-1-3-dig-t-160cv-acenta/img_10.jpg",
      "assets/cars/nissan-qashqai-1-3-dig-t-160cv-acenta/img_11.jpg",
      "assets/cars/nissan-qashqai-1-3-dig-t-160cv-acenta/img_12.jpg",
      "assets/cars/nissan-qashqai-1-3-dig-t-160cv-acenta/img_13.jpg",
      "assets/cars/nissan-qashqai-1-3-dig-t-160cv-acenta/img_14.jpg",
      "assets/cars/nissan-qashqai-1-3-dig-t-160cv-acenta/img_15.jpg",
      "assets/cars/nissan-qashqai-1-3-dig-t-160cv-acenta/img_16.jpg"
    ],
    "thumbnail": "assets/cars/nissan-qashqai-1-3-dig-t-160cv-acenta/img_01.jpg",
    "price_num": 18990,
    "cuota": "220 €/mes",
    "body_type": "SUV"
  },
  {
    "id": "renault-captur-intens-tce-140cv-mild-hibrido",
    "brand": "Renault",
    "title": "Renault Captur Intens TCE 140CV Mild Hybrid",
    "slug": "renault-captur-intens-tce-140cv-mild-hibrido",
    "specs": {
      "precio": "€1€7€.€4€9€0€ €€",
      "km": "59.000 km",
      "año": "28/01/2022",
      "combustible": "Gasolina Mild Hybrid",
      "cambio": "Manual 6 vel.",
      "color": "Blanco Nacardo / Techo Negro",
      "puertas": "5",
      "plazas": "sujeciones isofix",
      "etiqueta": "ECO",
      "potencia": "140 CV",
      "garantia": "Garantía 12 Meses Nacional y Cambio de Nombre incluidos"
    },
    "equipment": [
      "Versión : Intens TCe 103 kW (140CV) GPF mild hybrid -SS",
      "encendido automático de faros y sensor de lluvia",
      "indicador de cambio de marcha",
      "reconocimiento de señales de tráfico",
      "asistente mantenimiento de carril (lka)",
      "Sistema ECO-Mode",
      "control dinámico de trayectoria esc con ayuda al arranque en pendiente",
      "ayuda al aparcamiento delantero y trasero",
      "kit de reparación de neumáticos",
      "cámara de visión trasera",
      "regulador de velocidad",
      "tarjeta manos libres",
      "pack city (EXTRA)",
      "airbags laterales delanteros y cortina",
      "ayuda a la frenada de emergencia (safe)",
      "airbag frontal conductor y pasajero",
      "airbag pasajero desconectable",
      "aviso de los cinturones de seguridad delanteros y traseros desabrochadosl",
      "pack standard safety (EXTRA)",
      "Android Auto y Car Play",
      "driver display 4,2&quot;",
      "easy link conectado con pantalla táctil de 17,8cm (7&quot;) sin navegación",
      "climatizador automático",
      "filtro antipartículas",
      "pack comfort (EXTRA)",
      "consola central cerrada con reposabrazos",
      "Tapicería",
      "tapicería tejido gris y negro",
      "iluminación interior led plazas delanteras",
      "sujeciones isofix",
      "retrovisor interior día-noche",
      "asiento del conductor regulable en altura",
      "luces led delanteras y traseras",
      "elevalunas eléctricos traseros impulsionales",
      "elevalunas eléctricos delanteros impulsionales",
      "tiradores exteriores color carrocería",
      "retrovisores exteriores eléctricos abatibles eléctricamente",
      "Sin barras de techo",
      "retrovisores exteriores en color negro brillante",
      "embellecedores 43cm (17&#39;&#39;)",
      "embellecedores 43cm (17&#39;&#39;)",
      "carrocería bitono (techo, montantes y retrovisores exteriores)"
    ],
    "comments": "1 SOLO PROPIETARIO TODAS LAS REVISIONES PASADAS EN CONCESIONARIO RENAULT",
    "images": [
      "assets/cars/renault-captur-intens-tce-140cv-mild-hibrido/img_01.jpg",
      "assets/cars/renault-captur-intens-tce-140cv-mild-hibrido/img_02.jpg",
      "assets/cars/renault-captur-intens-tce-140cv-mild-hibrido/img_03.jpg",
      "assets/cars/renault-captur-intens-tce-140cv-mild-hibrido/img_04.jpg",
      "assets/cars/renault-captur-intens-tce-140cv-mild-hibrido/img_05.jpg",
      "assets/cars/renault-captur-intens-tce-140cv-mild-hibrido/img_06.jpg",
      "assets/cars/renault-captur-intens-tce-140cv-mild-hibrido/img_07.jpg",
      "assets/cars/renault-captur-intens-tce-140cv-mild-hibrido/img_08.jpg",
      "assets/cars/renault-captur-intens-tce-140cv-mild-hibrido/img_09.jpg",
      "assets/cars/renault-captur-intens-tce-140cv-mild-hibrido/img_10.jpg",
      "assets/cars/renault-captur-intens-tce-140cv-mild-hibrido/img_11.jpg",
      "assets/cars/renault-captur-intens-tce-140cv-mild-hibrido/img_12.jpg",
      "assets/cars/renault-captur-intens-tce-140cv-mild-hibrido/img_13.jpg",
      "assets/cars/renault-captur-intens-tce-140cv-mild-hibrido/img_14.jpg",
      "assets/cars/renault-captur-intens-tce-140cv-mild-hibrido/img_15.jpg",
      "assets/cars/renault-captur-intens-tce-140cv-mild-hibrido/img_16.jpg"
    ],
    "thumbnail": "assets/cars/renault-captur-intens-tce-140cv-mild-hibrido/img_01.jpg",
    "price_num": 17490,
    "cuota": "205 €/mes",
    "body_type": "SUV"
  },
  {
    "id": "renault-kadjar-tech-road",
    "brand": "Renault",
    "title": "Renault Kadjar 1.2 TCe Tech Road 130CV",
    "slug": "renault-kadjar-tech-road",
    "specs": {
      "precio": "€1€4€.€2€0€0€ €€",
      "km": "82.000 km",
      "año": "09/08/2018",
      "combustible": "Gasolina",
      "cambio": "Manual 6 vel.",
      "color": "Rojo Deseo",
      "puertas": "5",
      "plazas": "5",
      "etiqueta": "C",
      "potencia": "130 CV",
      "garantia": "Garantía 12 Meses Nacional y Cambio de Nombre incluidos"
    },
    "equipment": [
      "Climatizador bizona",
      "Sensor de aparcamiento delantero y trasero",
      "Sensor de luz y lluvia",
      "Elevalunas eléctricos",
      "Cierre centralizado",
      "Regulador / limitador de velocidad",
      "Control de estabilidad (ESC)",
      "Control de presión en neumáticos",
      "Control de tracción",
      "Alerta cambio de carril involuntario",
      "Alerta ángulo muerto",
      "Navegador",
      "Compatibilidad Apple CarPlay y Android Auto",
      "4 altavoces",
      "Conexión Bluetooth para telefóno móvil",
      "Conexión USB",
      "Airbag frontal conductor",
      "Airbag frontal pasajero",
      "Airbags de cabeza delanteros y traseros",
      "Airbags laterales delanteros",
      "Antibloqueo de frenos (ABS)",
      "Asistente de arranque en cuesta",
      "Ayuda a la frenada de urgencia",
      "Dirección asistida eléctrica variable",
      "Faros antiniebla con luz de giro",
      "Luces de día LED (DRL)",
      "Ordenador de viaje",
      "Retrovisores exteriores con calefacción",
      "Cristales laterales traseros sobretintados",
      "Freno de parking automático",
      "Función Stop &amp; Start",
      "Retrovisores exteriores abatibles eléctricamente",
      "Retrovisores exteriores con ajuste eléctrico",
      "Tarjeta manos libres",
      "Tapicería de tejido carbón oscuro",
      "Volante y pomo de palanca de cambios de cuero",
      "Kit de reparación de neumáticos",
      "Llantas de aleación de 17”"
    ],
    "comments": "Ha tenido 1 solo propietario particular.",
    "images": [
      "assets/cars/renault-kadjar-tech-road/img_01.jpg",
      "assets/cars/renault-kadjar-tech-road/img_02.jpg",
      "assets/cars/renault-kadjar-tech-road/img_03.jpg",
      "assets/cars/renault-kadjar-tech-road/img_04.jpg",
      "assets/cars/renault-kadjar-tech-road/img_05.jpg",
      "assets/cars/renault-kadjar-tech-road/img_06.jpg",
      "assets/cars/renault-kadjar-tech-road/img_07.jpg",
      "assets/cars/renault-kadjar-tech-road/img_08.jpg",
      "assets/cars/renault-kadjar-tech-road/img_09.jpg",
      "assets/cars/renault-kadjar-tech-road/img_10.jpg",
      "assets/cars/renault-kadjar-tech-road/img_11.jpg",
      "assets/cars/renault-kadjar-tech-road/img_12.jpg",
      "assets/cars/renault-kadjar-tech-road/img_13.jpg",
      "assets/cars/renault-kadjar-tech-road/img_14.jpg",
      "assets/cars/renault-kadjar-tech-road/img_15.jpg",
      "assets/cars/renault-kadjar-tech-road/img_16.jpg"
    ],
    "thumbnail": "assets/cars/renault-kadjar-tech-road/img_01.jpg",
    "price_num": 14200,
    "cuota": "165 €/mes",
    "body_type": "SUV"
  },
  {
    "id": "renault-megane-1-5-dci-sport-tourer-115cv",
    "brand": "Renault",
    "title": "Renault Megane 1.5 dCi Sport Tourer 115CV",
    "slug": "renault-megane-1-5-dci-sport-tourer-115cv",
    "specs": {
      "precio": "€1€3€.€4€9€0€ €€",
      "km": "83.000 km",
      "año": "02/12/2020",
      "combustible": "Diésel",
      "cambio": "Manual 6 vel.",
      "color": "Blanco Glaciar",
      "puertas": "5",
      "plazas": "Antibloqueo de frenos (ABS)",
      "etiqueta": "C",
      "potencia": "115 CV",
      "garantia": "Garantía 12 Meses Nacional y Cambio de Nombre incluidos"
    },
    "equipment": [
      "Pintura Blanco Glaciar",
      "Climatizador bizona",
      "Cierre centralizado",
      "Elevalunas eléctricos",
      "Función Stop&amp;Start",
      "Luces automáticas",
      "Limpiaparabrisas automático",
      "Control de estabilidad",
      "Control de tracción",
      "Control de distancia de aparcamiento trasero",
      "Regulador-limitador de velocidad",
      "Cuadro de instrumentos con pantalla TFT de 17,8 cm (7&quot;) en color",
      "Radio",
      "Pantalla táctil de 17,8 cm (7&quot;) Easy Link",
      "Conexión Bluetooth para teléfono móvil",
      "Compatibilidad con Android Auto y Apple CarPlay",
      "2 tomas USB delante y 2 USB para cargar detrás",
      "Volante en símil cuero multifunción",
      "Faros Full LED Pure Vision",
      "Control de presión en neumáticos",
      "Luces traseras 3D Edge Light con intermitentes dinámicos",
      "Airbag frontal conductor",
      "Airbag frontal pasajero",
      "Airbags de cabeza delanteros y traseros",
      "Airbags laterales delanteros",
      "Anclajes ISOFIX en plazas laterales traseras",
      "Antibloqueo de frenos (ABS)",
      "Asistencia a la frenada de emergencia",
      "Ayuda al arranque en pendiente",
      "Luz diurna LED (firma luminosa C-shape)",
      "Ordenador de viaje",
      "Retrovisores exteriores con calefacción",
      "Apoyabrazos central delantero",
      "Asiento del conductor con ajuste de altura",
      "Asiento del conductor con ajuste lumbar",
      "Mando de apertura a distancia",
      "Retrovisores exteriores orientables eléctricamente",
      "Tarjeta manos libres",
      "Luces traseras 3D Edge Light con intermitentes dinámicos",
      "Tiradores exteriores con junco cromado"
    ],
    "comments": "",
    "images": [
      "assets/cars/renault-megane-1-5-dci-sport-tourer-115cv/img_01.jpg",
      "assets/cars/renault-megane-1-5-dci-sport-tourer-115cv/img_02.jpg",
      "assets/cars/renault-megane-1-5-dci-sport-tourer-115cv/img_03.jpg",
      "assets/cars/renault-megane-1-5-dci-sport-tourer-115cv/img_04.jpg",
      "assets/cars/renault-megane-1-5-dci-sport-tourer-115cv/img_05.jpg",
      "assets/cars/renault-megane-1-5-dci-sport-tourer-115cv/img_06.jpg",
      "assets/cars/renault-megane-1-5-dci-sport-tourer-115cv/img_07.jpg",
      "assets/cars/renault-megane-1-5-dci-sport-tourer-115cv/img_08.jpg",
      "assets/cars/renault-megane-1-5-dci-sport-tourer-115cv/img_09.jpg",
      "assets/cars/renault-megane-1-5-dci-sport-tourer-115cv/img_10.jpg",
      "assets/cars/renault-megane-1-5-dci-sport-tourer-115cv/img_11.jpg",
      "assets/cars/renault-megane-1-5-dci-sport-tourer-115cv/img_12.jpg",
      "assets/cars/renault-megane-1-5-dci-sport-tourer-115cv/img_13.jpg",
      "assets/cars/renault-megane-1-5-dci-sport-tourer-115cv/img_14.jpg",
      "assets/cars/renault-megane-1-5-dci-sport-tourer-115cv/img_15.jpg",
      "assets/cars/renault-megane-1-5-dci-sport-tourer-115cv/img_16.jpg"
    ],
    "thumbnail": "assets/cars/renault-megane-1-5-dci-sport-tourer-115cv/img_01.jpg",
    "price_num": 13490,
    "cuota": "155 €/mes",
    "body_type": "Familiar"
  },
  {
    "id": "toyota-corolla-9479-lvw",
    "brand": "Toyota",
    "title": "Toyota Corolla 1.8 125H Active Tech",
    "slug": "toyota-corolla-9479-lvw",
    "specs": {
      "precio": "€2€1€.€4€9€0€ €€",
      "km": "42.000 km",
      "año": "13/01/2022",
      "combustible": "Híbrido Gasolina",
      "cambio": "Automático e-CVT",
      "color": "Gris Manhattan",
      "puertas": "5",
      "plazas": "5",
      "etiqueta": "ECO",
      "potencia": "122 CV",
      "garantia": "Garantía 12 Meses Nacional y Cambio de Nombre incluidos"
    },
    "equipment": [
      "Climatizador bizona",
      "Control de crucero adaptativo",
      "Control de estabilidad (VSC+)",
      "Control de presión en neumáticos",
      "Control de tracción",
      "Control inteligente de luces de carretera",
      "Cámara de visión trasera",
      "Volante y palanca de cambio de cuero",
      "6 altavoces",
      "Conexión AUX y USB",
      "Conexión Bluetooth con audio streaming",
      "Integración móvil (Apple CarPlay y Android Auto)",
      "Pantalla de 20,3 cm (8&quot;) Toyota Touch 2",
      "Radio digital DAB",
      "9 Airbags",
      "Alerta de pérdida de atención del conductor",
      "Asistencia a la frenada (BA)",
      "Asistente de arranque en pendiente",
      "Asistente de cambio involuntario de carril",
      "Avisador de cambio involuntario de carril",
      "Aviso acústico para peatones (Acoustic Vehicle Alerting System)",
      "Distribución electrónica de frenado (EBD)",
      "Faros antiniebla LED",
      "Faros parábola LED",
      "Luz diurna LED",
      "Mandos multifunción en volante",
      "Ordenador de viaje",
      "Reconocimiento de señales de tráfico",
      "Seguridad precolisión con detector de peatones y ciclistas",
      "Selección de modos de conducción (ECO, EV, SPORT)",
      "Arranque sin llave (Push Start)",
      "Entrada sin llave (SME)",
      "Sensor de luz y lluvia",
      "Lunas tintadas",
      "Retrovisores exteriores plegables eléctricamente",
      "Cuadro de instrumentos con pantalla a color de 17,8 cm (7&quot;)",
      "Luces traseras LED",
      "Parrilla frontal con embellecedores Black piano",
      "Pintura metalizada",
      "Reconocimiento de voz"
    ],
    "comments": "TODAS LAS REVISIONES EN SERVICIO OFICIAL GARANTIA TOYOTA RELAX",
    "images": [
      "assets/cars/toyota-corolla-9479-lvw/img_01.jpg",
      "assets/cars/toyota-corolla-9479-lvw/img_02.jpg",
      "assets/cars/toyota-corolla-9479-lvw/img_03.jpg",
      "assets/cars/toyota-corolla-9479-lvw/img_04.jpg",
      "assets/cars/toyota-corolla-9479-lvw/img_05.jpg",
      "assets/cars/toyota-corolla-9479-lvw/img_06.jpg",
      "assets/cars/toyota-corolla-9479-lvw/img_07.jpg",
      "assets/cars/toyota-corolla-9479-lvw/img_08.jpg",
      "assets/cars/toyota-corolla-9479-lvw/img_09.jpg",
      "assets/cars/toyota-corolla-9479-lvw/img_10.jpg",
      "assets/cars/toyota-corolla-9479-lvw/img_11.jpg",
      "assets/cars/toyota-corolla-9479-lvw/img_12.jpg",
      "assets/cars/toyota-corolla-9479-lvw/img_13.jpg",
      "assets/cars/toyota-corolla-9479-lvw/img_14.jpg",
      "assets/cars/toyota-corolla-9479-lvw/img_15.jpg",
      "assets/cars/toyota-corolla-9479-lvw/img_16.jpg"
    ],
    "thumbnail": "assets/cars/toyota-corolla-9479-lvw/img_01.jpg",
    "price_num": 21490,
    "cuota": "250 €/mes",
    "body_type": "Compacto"
  },
  {
    "id": "toyota-corolla-125h-style-ecvt",
    "brand": "Toyota",
    "title": "Toyota Corolla 1.8 125H Style e-CVT",
    "slug": "toyota-corolla-125h-style-ecvt",
    "specs": {
      "precio": "€2€0€.€9€0€0€ €€",
      "km": "48.000 km",
      "año": "2021",
      "combustible": "Híbrido Gasolina",
      "cambio": "Automático e-CVT",
      "color": "Blanco Perlado",
      "puertas": "5",
      "plazas": "5",
      "etiqueta": "ECO",
      "potencia": "122 CV",
      "garantia": "Garantía 12 Meses Nacional y Cambio de Nombre incluidos"
    },
    "equipment": [
      "Llantas de 17&quot;",
      "Volante de piel multifunción.",
      "ANDROID AUTO-APPLE CAR",
      "Navegador",
      "Arranque sin llave",
      "Parktronic delantero",
      "Parktronic trasero",
      "Bluetooth",
      "Pantalla multimedia",
      "Freno estacionamiento electrónico",
      "Control de crucero adaptativo",
      "limitador de velocidad",
      "Control asistencia arranque en pendientes",
      "Entrada USB",
      "Climatizador bizona",
      "Star/Stop",
      "Control de estabilidad",
      "Isofix",
      "Reposacodos con guantera",
      "Ordenador de abordo",
      "Isofix",
      "Asistente y avisador de cambio involuntario de carril",
      "Control de presión de neumáticos",
      "Cámara visión trasera",
      "Faros multiled",
      "Faros antiniebla led",
      "Retrovisores plegables eléctricamente",
      "Tapiceria de piel mixta"
    ],
    "comments": "Ha tenido 1 solo propietario particular.",
    "images": [
      "assets/cars/toyota-corolla-125h-style-ecvt/img_01.jpg",
      "assets/cars/toyota-corolla-125h-style-ecvt/img_02.jpg",
      "assets/cars/toyota-corolla-125h-style-ecvt/img_03.jpg",
      "assets/cars/toyota-corolla-125h-style-ecvt/img_04.jpg",
      "assets/cars/toyota-corolla-125h-style-ecvt/img_05.jpg",
      "assets/cars/toyota-corolla-125h-style-ecvt/img_06.jpg",
      "assets/cars/toyota-corolla-125h-style-ecvt/img_07.jpg",
      "assets/cars/toyota-corolla-125h-style-ecvt/img_08.jpg",
      "assets/cars/toyota-corolla-125h-style-ecvt/img_09.jpg",
      "assets/cars/toyota-corolla-125h-style-ecvt/img_10.jpg",
      "assets/cars/toyota-corolla-125h-style-ecvt/img_11.jpg",
      "assets/cars/toyota-corolla-125h-style-ecvt/img_12.jpg",
      "assets/cars/toyota-corolla-125h-style-ecvt/img_13.jpg",
      "assets/cars/toyota-corolla-125h-style-ecvt/img_14.jpg",
      "assets/cars/toyota-corolla-125h-style-ecvt/img_15.jpg",
      "assets/cars/toyota-corolla-125h-style-ecvt/img_16.jpg"
    ],
    "thumbnail": "assets/cars/toyota-corolla-125h-style-ecvt/img_01.jpg",
    "price_num": 20900,
    "cuota": "245 €/mes",
    "body_type": "Compacto"
  },
  {
    "id": "toyota-yaris-120h-gr-sport-plus",
    "brand": "Toyota",
    "title": "Toyota Yaris 120H GR Sport Plus",
    "slug": "toyota-yaris-120h-gr-sport-plus",
    "specs": {
      "precio": "€2€0€.€9€9€0€ €€",
      "km": "52.000 km",
      "año": "04/01/2023",
      "combustible": "Híbrido Gasolina",
      "cambio": "Automático e-CVT",
      "color": "Gris Dynamic Bi-tono",
      "puertas": "5",
      "plazas": "Antibloqueo de frenos (ABS)",
      "etiqueta": "ECO",
      "potencia": "116 CV",
      "garantia": "Garantía Toyota Relax hasta 15 años"
    },
    "equipment": [
      "Tapicería de cuero y Alcantara GR Sport con pespunte rojo",
      "Asientos delanteros deportivos GR Sport",
      "Volante de cuero perforado con pespunte rojo y pomo de cambio en cuero",
      "Paragolpes GR Sport",
      "Parrilla delantera negra diseño panal de abeja",
      "Suspensión deportiva",
      "Llantas de aleación 46 cm (215/40 R18) GR Sport",
      "Color gris Ascari bitono",
      "6 altavoces",
      "Android Auto y Apple CarPlay inalámbrico",
      "Cargador inalámbrico para teléfono móvil",
      "Conexión Bluetooth para teléfono móvil",
      "Conexión USB",
      "Navegador",
      "Pantalla táctil de 22,9 cm (9&quot;)",
      "Airbag frontal conductor",
      "Airbag frontal pasajero",
      "Airbags de cabeza delanteros y traseros",
      "Airbags laterales delanteros",
      "Alerta de cambio involuntario de carril",
      "Alerta de fatiga del conductor",
      "Anclajes ISOFIX en plazas traseras",
      "Antibloqueo de frenos (ABS)",
      "Asistencia a la frenada (BA)",
      "Asistente de arranque en pendiente (HAC)",
      "Asistente de cambio involuntario de carril",
      "Aviso de frenada de emergencia (EBS)",
      "Control de crucero adaptativo",
      "Control de estabilidad (VSC)",
      "Control de presión de neumáticos",
      "Control de tracción",
      "Control inteligente de luces de carretera (AHB)",
      "Cámara de visión trasera",
      "Dirección asistida eléctrica (EPS)",
      "Distribución electrónica de frenado (EBD)",
      "Faros LED",
      "Faros antiniebla LED",
      "Limitador de velocidad",
      "Luz diurna",
      "Mandos multifunción en volante",
      "Ordenador de viaje",
      "Reconocimiento de señales de tráfico",
      "Reposacabezas delanteros antilatigazo cervical",
      "Retrovisor interior electrocrómico",
      "Retrovisores exteriores con calefacción",
      "Seguridad precolisión con detector de peatones y ciclistas",
      "Acceso sin llave",
      "Apoyabrazos central delantero",
      "Arranque sin llave",
      "Cierre centralizado",
      "Climatizador bizona",
      "Elevalunas eléctricos delanteros y traseros",
      "Encendido y parada automáticos del motor térmico",
      "Faros con función Follow me home",
      "Freno de estacionamiento automático",
      "Limpiaparabrisas automático",
      "Luces automáticas",
      "Lunas tintadas",
      "Lunas traseras sobretintadas",
      "Mando de apertura a distancia",
      "Retrovisores exteriores orientables eléctricamente",
      "Carcasas de retrovisores exteriores en negro",
      "Cuadro de instrumentos con pantalla TFT de 10,7 cm (4,2&quot;)",
      "Luces traseras LED",
      "Paragolpes en color carrocería",
      "Pedales en aluminio",
      "Techo pintado en negro",
      "Tiradores exteriores en color carrocería",
      "Equipo reparapinchazos",
      "Aplicación MyT (información del vehículo a distancia)",
      "Recuperación de la energía de frenado"
    ],
    "comments": "PROCEDENCIA PARTICULAR Todas las revisiones en servicio oficial. GARANTIA TOYOTA RELAX 15 AÑOS Ó 250.000KM",
    "images": [
      "assets/cars/toyota-yaris-120h-gr-sport-plus/img_01.jpg",
      "assets/cars/toyota-yaris-120h-gr-sport-plus/img_02.jpg",
      "assets/cars/toyota-yaris-120h-gr-sport-plus/img_03.jpg",
      "assets/cars/toyota-yaris-120h-gr-sport-plus/img_04.jpg",
      "assets/cars/toyota-yaris-120h-gr-sport-plus/img_05.jpg",
      "assets/cars/toyota-yaris-120h-gr-sport-plus/img_06.jpg",
      "assets/cars/toyota-yaris-120h-gr-sport-plus/img_07.jpg",
      "assets/cars/toyota-yaris-120h-gr-sport-plus/img_08.jpg",
      "assets/cars/toyota-yaris-120h-gr-sport-plus/img_09.jpg",
      "assets/cars/toyota-yaris-120h-gr-sport-plus/img_10.jpg",
      "assets/cars/toyota-yaris-120h-gr-sport-plus/img_11.jpg",
      "assets/cars/toyota-yaris-120h-gr-sport-plus/img_12.jpg",
      "assets/cars/toyota-yaris-120h-gr-sport-plus/img_13.jpg",
      "assets/cars/toyota-yaris-120h-gr-sport-plus/img_14.jpg",
      "assets/cars/toyota-yaris-120h-gr-sport-plus/img_15.jpg",
      "assets/cars/toyota-yaris-120h-gr-sport-plus/img_16.jpg"
    ],
    "thumbnail": "assets/cars/toyota-yaris-120h-gr-sport-plus/img_01.jpg",
    "price_num": 20990,
    "cuota": "245 €/mes",
    "body_type": "Compacto"
  },
  {
    "id": "vw-passat-variant-1-6-tdi-120cv",
    "brand": "Volkswagen",
    "title": "Volkswagen Passat Variant 1.6 TDI 120CV",
    "slug": "vw-passat-variant-1-6-tdi-120cv",
    "specs": {
      "precio": "€1€7€.€9€9€0€ €€",
      "km": "160.000 km",
      "año": "27/12/2017",
      "combustible": "Diésel",
      "cambio": "Manual 6 vel.",
      "color": "Negro Profundo",
      "puertas": "Plazas: 5",
      "plazas": "E",
      "etiqueta": "C",
      "potencia": "120 CV",
      "garantia": "Garantía 12 Meses Nacional y Cambio de Nombre incluidos"
    },
    "equipment": [
      "Llantas de 16&quot;",
      "Volante de piel multifunción.",
      "ANDROID AUTO-APPLE CAR-MIRROR LINK",
      "Arranque sin llave",
      "Parktronic delantero",
      "Parktronic trasero",
      "Bluetooth",
      "Pantalla multimedia",
      "Freno estacionamiento electrónico",
      "Control cruise",
      "Control asistencia arranque en pendientes",
      "Entrada USB+AUX",
      "Aire acondicionado",
      "Star/Stop",
      "Control de estabilidad",
      "Isofix",
      "Reposacodos con guantera",
      "Ordenador de abordo",
      "Cubre equipajes enrollable",
      "Faros antiniebla"
    ],
    "comments": "&quot;&quot;&quot;MATRICULADO EL 27-12-2017&quot;&quot;&quot; &quot;&quot;&quot;GARANTIA 12 MESES&quot;&quot;&quot; Coche nacional con libro de revisiones oficial. El coche esta muy bien cuidado Si deseas financiarlo puedes hacerlo con nosotros con unas excelentes condiciones.",
    "images": [
      "assets/cars/vw-passat-variant-1-6-tdi-120cv/img_01.jpg",
      "assets/cars/vw-passat-variant-1-6-tdi-120cv/img_02.jpg",
      "assets/cars/vw-passat-variant-1-6-tdi-120cv/img_03.jpg",
      "assets/cars/vw-passat-variant-1-6-tdi-120cv/img_04.jpg",
      "assets/cars/vw-passat-variant-1-6-tdi-120cv/img_05.jpg",
      "assets/cars/vw-passat-variant-1-6-tdi-120cv/img_06.jpg",
      "assets/cars/vw-passat-variant-1-6-tdi-120cv/img_07.jpg",
      "assets/cars/vw-passat-variant-1-6-tdi-120cv/img_08.jpg",
      "assets/cars/vw-passat-variant-1-6-tdi-120cv/img_09.jpg",
      "assets/cars/vw-passat-variant-1-6-tdi-120cv/img_10.jpg",
      "assets/cars/vw-passat-variant-1-6-tdi-120cv/img_11.jpg",
      "assets/cars/vw-passat-variant-1-6-tdi-120cv/img_12.jpg",
      "assets/cars/vw-passat-variant-1-6-tdi-120cv/img_13.jpg",
      "assets/cars/vw-passat-variant-1-6-tdi-120cv/img_14.jpg",
      "assets/cars/vw-passat-variant-1-6-tdi-120cv/img_15.jpg",
      "assets/cars/vw-passat-variant-1-6-tdi-120cv/img_16.jpg"
    ],
    "thumbnail": "assets/cars/vw-passat-variant-1-6-tdi-120cv/img_01.jpg",
    "price_num": 17990,
    "cuota": "210 €/mes",
    "body_type": "Familiar"
  }
];
